# This is a basic workflow to help you get started with Actions

name: Create thermals.mbtiles + thermals.brokjson.zip

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    paths:
      - '*.geojson'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  list-files:
      runs-on: ubuntu-latest
      outputs:
        paths: ${{ steps.list-files.outputs.paths }}
      steps:
        - name: List Files
          id: list-files
          uses: mirko-felice/list-files-action@v3.0.1
          with:
            repo: ${{ github.repository }}
            ref: ${{ github.ref }}
            path: "."
            ext: ".geojson"

  # This workflow contains a single job called "build"
  build_mbtiles:
    needs: list-files
    strategy:
      matrix:
        paths: ${{ fromJson(needs.list-files.outputs.paths) }}

    if: ${{ github.ref == 'refs/heads/master' }}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Output results
        run: |
          echo ${{ matrix.paths }}

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Clone this repo=thermalmap-geojson-data + thermalmap-tippecanoe repo 
        uses: actions/checkout@v3
      
      # This part here is cloning a second repository
      # While cloning the repository:
      #   - it clones the repo into the given `path`
      #   - it checks out the branch defined at `ref`
      - name: Clone thermalmap-tippecanoe repo
        uses: actions/checkout@v2
        with:
          repository: llauner/thermalmap-tippecanoe
          path: ./tippecanoe
          ref: master

      # Install tippecanoe
      - name: Install tippecanoe
        run: |
          cd tippecanoe
          sudo make -j
          sudo make install

      # Runs tippecannoe
      - name: Run tippecanoe to generate tiles
        run: |
          CURRENT_FILE=${{ matrix.paths }}
          CURRENT_FILE_NAME=$(basename -- "$CURRENT_FILE")
          CURRENT_FILE_NAME="${CURRENT_FILE_NAME%.*}"
          echo "Converting...: ${{ matrix.paths }} -> $CURRENT_FILE_NAME.mbtiles"

          tippecanoe -r1 -z12 --progress-interval=20 --drop-densest-as-needed --extend-zooms-if-still-dropping  -o $CURRENT_FILE_NAME.mbtiles ${{ matrix.paths }} --force
     
      # Push changes to repo
      - name: git pull
        run: git pull    
      - name: Push changes into repo
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated Change
          skip_dirty_check: true
          push_options: '--force'
          file_pattern: '*.mbtiles'

  build_brokjson:
    needs: [list-files]
    strategy:
      matrix:
        paths: ${{ fromJson(needs.list-files.outputs.paths) }}

    name: Build brokjson file from geojson
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest

    steps:
      - name: Install Zip
        run: |
          sudo apt install zip

      - name: Clone thermal_map
        uses: actions/checkout@v3
        with:
          repository: llauner/thermal_map
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: ./thermal_map
          ref: master

      - name: Clone thermalmap-geojson-data repo
        uses: actions/checkout@v3
        with:
          path: ./thermalmap-geojson-data
          ref: master
          
      - uses: actions/setup-python@v4
        with:
            python-version: 3.7

      - name: Install thermal_map and create thermals.brokjson.zip
        id: thermal_map
        run: |
          CURRENT_FILE=${{ matrix.paths }}
          CURRENT_FILE_NAME=$(basename -- "$CURRENT_FILE")
          CURRENT_FILE_NAME="${CURRENT_FILE_NAME%.*}"
          cd ./thermal_map
          python -VV
          pip install -r requirements_main.txt
          python main_geojson2brokjson.py ../thermalmap-geojson-data/${CURRENT_FILE_NAME}.geojson ../thermalmap-geojson-data/$CURRENT_FILE_NAME.brokjson
          zip ../thermalmap-geojson-data/$CURRENT_FILE_NAME.brokjson.zip ../thermalmap-geojson-data/$CURRENT_FILE_NAME.brokjson
          cd ../thermalmap-geojson-data
          echo "CURRENT_FILE_NAME=$CURRENT_FILE_NAME" >> $GITHUB_OUTPUT

      # Push changes to repo    
      - name: git pull
        run: |
          cd ./thermalmap-geojson-data
          git pull   
      - name: Push changes into repo
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          repository: ./thermalmap-geojson-data
          commit_message: Automated Change
          skip_dirty_check: true
          push_options: '--force'
          file_pattern: '${{ steps.thermal_map.outputs.CURRENT_FILE_NAME }}.brokjson.zip'


  # push-event-to-other-repo:
  #   needs: [build_mbtiles, build_brokjson]
  #   name: Dispatch to other repo= thermalmap-tilehut-server
  #   if: false
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Emit repository_dispatch
  #       uses: mvasigh/dispatch-action@main
  #       with:
  #         # You should create a personal access token and store it in your repository
  #         token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  #         repo: thermalmap-tilehut-server
  #         owner: llauner
  #         event_type: external_push_mbtiles_created
    
