# This is a basic workflow to help you get started with Actions

name: test

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  list-files:
      runs-on: ubuntu-latest
      outputs:
        paths: ${{ steps.list-files.outputs.paths }}
      steps:
        - name: List Files
          id: list-files
          uses: mirko-felice/list-files-action@v3.0.1
          with:
            repo: ${{ github.repository }}
            ref: ${{ github.ref }}
            path: "."
            ext: ".geojson"

  # This workflow contains a single job called "build"
  build_mbtiles:
    needs: list-files
    if: ${{ github.ref == 'refs/heads/master' }}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Output results
        run: |
          echo ${{ fromJson(needs.list-files.outputs.paths) }}