# This is a basic workflow to help you get started with Actions

name: test

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:


  # This workflow contains a single job called "build"
  build_mbtiles:
    if: ${{ github.ref == 'refs/heads/master' }}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Clone this repo=thermalmap-geojson-data + thermalmap-tippecanoe repo 
        uses: actions/checkout@v3
      
      - name: list
        run: |
          for fileName in $(ls); do
            echo $fileName
          done